language: c

sudo: true

install:
  - sudo apt-add-repository -y ppa:zoogie/sdl2-snapshots
  - sudo apt-get update
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

compiler:
  - clang
  - gcc

script:
  - make -e
